// Derives the Mediterranean side of the map from the same geoBoundaries ADM0 outline and the
// same projection as scripts/prepare-map.mjs, so the sea polygon follows the real coastline.
// Output: data/lebanon-sea.ts (a closed polygon covering everything west of the coast).
import fs from "node:fs/promises";
import { geoArea, geoMercator } from "d3-geo";

const national = JSON.parse(await fs.readFile("public/maps/lebanon-adm0.geojson", "utf8"));
// d3-geo's spherical polygon convention is the reverse of RFC 7946 winding (same fix as prepare-map.mjs).
for (const feature of national.features) {
  if (geoArea(feature) > 2 * Math.PI) {
    const rings = feature.geometry.type === "Polygon" ? [feature.geometry.coordinates] : feature.geometry.coordinates;
    rings.forEach((polygon) => polygon.forEach((ring) => ring.reverse()));
  }
}
const projection = geoMercator().fitExtent([[90, 32], [495, 630]], national);

// Use the mainland only (ignore offshore islands).
const polygons = national.features.flatMap((feature) =>
  feature.geometry.type === "Polygon" ? [feature.geometry.coordinates] : feature.geometry.coordinates,
);
const planarArea = (points) =>
  Math.abs(
    points.reduce((sum, [x1, y1], i) => {
      const [x2, y2] = points[(i + 1) % points.length];
      return sum + (x1 * y2 - x2 * y1);
    }, 0) / 2,
  );
const ring = polygons
  .map((coordinates) => coordinates[0].map((point) => projection(point)))
  .sort((a, b) => planarArea(a) - planarArea(b))
  .at(-1);

const step = 4;
const top = Math.min(...ring.map((p) => p[1]));
const bottom = Math.max(...ring.map((p) => p[1]));
const coast = [];
for (let y = Math.ceil(top / step) * step; y <= bottom; y += step) {
  let minX = Infinity;
  for (let i = 0; i < ring.length - 1; i++) {
    const [x1, y1] = ring[i];
    const [x2, y2] = ring[i + 1];
    if ((y1 <= y && y2 > y) || (y2 <= y && y1 > y)) {
      minX = Math.min(minX, x1 + ((y - y1) / (y2 - y1)) * (x2 - x1));
    }
  }
  if (Number.isFinite(minX)) coast.push([minX, y]);
}
// The northern tip follows the border with Syria, not the sea: start where the coast begins
// (the first large westward jump).
const start = coast.findIndex((point, i) => i > 0 && point[0] < coast[i - 1][0] - 30);
if (start > 0) coast.splice(0, start);
const r = (v) => Math.round(v * 10) / 10;
const first = coast[0];
const last = coast.at(-1);
// The northern edge slants away from the coast so there is no hard vertical wall of "sea" above
// the Syrian border.
const path = [
  "M-400 -120",
  `L${r(first[0] - 130)} -120`,
  ...coast.map(([x, y]) => `L${r(x)} ${r(y)}`),
  `L${r(last[0])} 800`,
  "L-400 800Z",
].join("");
await fs.writeFile(
  "data/lebanon-sea.ts",
  `// Generated by scripts/prepare-sea.mjs from geoBoundaries ADM0. Do not edit by hand.\n// Polygon covering the Mediterranean side of the map (everything west of the coastline).\nexport const seaPath = "${path}";\n`,
);
console.log(`sea polygon: ${coast.length} coast points, ${path.length} chars; coast x range ${r(Math.min(...coast.map((p) => p[0])))}..${r(Math.max(...coast.map((p) => p[0])))}`);
